/*
    SHRP Theme Builder
    Copyright (C) 2020  epicX

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
package com.shrp.themes;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author epicX
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbColorType = new javax.swing.ButtonGroup();
        dType = new javax.swing.ButtonGroup();
        nType = new javax.swing.ButtonGroup();
        mainBasePanel = new javax.swing.JPanel();
        topBar = new javax.swing.JPanel();
        minBtn = new javax.swing.JButton();
        appLogo = new javax.swing.JLabel();
        appTitle = new javax.swing.JLabel();
        sideBarMainSec = new javax.swing.JLabel();
        sideBarMainSec2 = new javax.swing.JLabel();
        sideBarSubSec1 = new javax.swing.JLabel();
        colorSelected = new javax.swing.JSeparator();
        colorTypeSwitcher = new javax.swing.JLabel();
        configSelected = new javax.swing.JSeparator();
        sideBarSubSec3 = new javax.swing.JLabel();
        authorName = new javax.swing.JLabel();
        sideBar = new javax.swing.JLabel();
        chPlainColor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bColor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        aColor = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        pTextColor = new javax.swing.JTextField();
        sTextColor = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dColor1 = new javax.swing.JTextField();
        dColor1S = new javax.swing.JSeparator();
        dColorLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dColor2 = new javax.swing.JTextField();
        dColor2S = new javax.swing.JSeparator();
        dColor3 = new javax.swing.JTextField();
        dColor3S = new javax.swing.JSeparator();
        dColor4S = new javax.swing.JSeparator();
        dColor4 = new javax.swing.JTextField();
        dColor5S = new javax.swing.JSeparator();
        dColor5 = new javax.swing.JTextField();
        dColor6S = new javax.swing.JSeparator();
        dColor6 = new javax.swing.JTextField();
        plainNextBtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        chGradientColor = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        gbColor = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        gaColor = new javax.swing.JTextField();
        gaColor1S = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        gpTextColor = new javax.swing.JTextField();
        gsTextColor = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        gdColor1 = new javax.swing.JTextField();
        gdColor1S = new javax.swing.JSeparator();
        gdColorLabel = new javax.swing.JLabel();
        gcolorSwitch = new javax.swing.JLabel();
        gdColor2 = new javax.swing.JTextField();
        gdColor2S = new javax.swing.JSeparator();
        gdColor3 = new javax.swing.JTextField();
        gdColor3S = new javax.swing.JSeparator();
        gdColor4S = new javax.swing.JSeparator();
        gdColor4 = new javax.swing.JTextField();
        gdColor5S = new javax.swing.JSeparator();
        gdColor5 = new javax.swing.JTextField();
        gdColor6S = new javax.swing.JSeparator();
        gdColor6 = new javax.swing.JTextField();
        lrBtn = new javax.swing.JRadioButton();
        tbBtn = new javax.swing.JRadioButton();
        tlbrBtn = new javax.swing.JRadioButton();
        trblBtn = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        gaColor2 = new javax.swing.JTextField();
        gaColor2S = new javax.swing.JSeparator();
        gradientButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        configurationPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        executeBtn = new javax.swing.JButton();
        dIcoDefault = new javax.swing.JRadioButton();
        dIcoMaterial = new javax.swing.JRadioButton();
        dIcoPlain = new javax.swing.JRadioButton();
        nIcoPie = new javax.swing.JRadioButton();
        nIcoNxtbit = new javax.swing.JRadioButton();
        nIcoSamsung = new javax.swing.JRadioButton();
        nIcoCustom = new javax.swing.JRadioButton();
        prevBtn = new javax.swing.JButton();
        mExecuteStatus = new javax.swing.JLabel();
        sExecuteStatus = new javax.swing.JLabel();
        thNameLabel = new javax.swing.JLabel();
        thName = new javax.swing.JTextField();
        thNameS = new javax.swing.JSeparator();
        cleanupBtn = new javax.swing.JButton();
        versionLabel = new javax.swing.JLabel();
        helpPanel = new javax.swing.JPanel();
        helpHeader = new javax.swing.JLabel();
        helpSubTxt1 = new javax.swing.JLabel();
        helpSubTxt2 = new javax.swing.JLabel();
        helpSubTxt3 = new javax.swing.JLabel();
        helpSubTxt4 = new javax.swing.JLabel();
        closeBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainFrame"); // NOI18N
        setUndecorated(true);

        mainBasePanel.setBackground(new java.awt.Color(28, 28, 40));
        mainBasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBar.setBackground(new java.awt.Color(28, 28, 40));
        topBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topBarMouseDragged(evt);
            }
        });
        topBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topBarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topBarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        topBarLayout.setVerticalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        mainBasePanel.add(topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 520, 40));

        minBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/min.png"))); // NOI18N
        minBtn.setBorderPainted(false);
        minBtn.setContentAreaFilled(false);
        minBtn.setFocusPainted(false);
        minBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minBtnActionPerformed(evt);
            }
        });
        mainBasePanel.add(minBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 10, 30, -1));

        appLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/shrpLogo.png"))); // NOI18N
        mainBasePanel.add(appLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, 20));

        appTitle.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        appTitle.setForeground(new java.awt.Color(240, 240, 240));
        appTitle.setText("theme builder");
        mainBasePanel.add(appTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 12, -1, -1));

        sideBarMainSec.setFont(new java.awt.Font("Steradian Regular", 0, 18)); // NOI18N
        sideBarMainSec.setForeground(new java.awt.Color(255, 255, 255));
        sideBarMainSec.setText("Style");
        mainBasePanel.add(sideBarMainSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        sideBarMainSec2.setFont(new java.awt.Font("Steradian Regular", 0, 18)); // NOI18N
        sideBarMainSec2.setForeground(new java.awt.Color(255, 255, 255));
        sideBarMainSec2.setText("Color");
        mainBasePanel.add(sideBarMainSec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        sideBarSubSec1.setFont(new java.awt.Font("Steradian Regular", 0, 14)); // NOI18N
        sideBarSubSec1.setForeground(new java.awt.Color(255, 255, 255));
        sideBarSubSec1.setText("Plain color");
        mainBasePanel.add(sideBarSubSec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, -1));

        colorSelected.setForeground(new java.awt.Color(255, 255, 255));
        colorSelected.setOrientation(javax.swing.SwingConstants.VERTICAL);
        mainBasePanel.add(colorSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 10, 20));

        colorTypeSwitcher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/toggleOff.png"))); // NOI18N
        colorTypeSwitcher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorTypeSwitcherMouseClicked(evt);
            }
        });
        mainBasePanel.add(colorTypeSwitcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 111, -1, -1));

        configSelected.setForeground(new java.awt.Color(255, 255, 255));
        configSelected.setOrientation(javax.swing.SwingConstants.VERTICAL);
        mainBasePanel.add(configSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 10, 20));
        configSelected.setVisible(false);

        sideBarSubSec3.setFont(new java.awt.Font("Steradian Regular", 0, 14)); // NOI18N
        sideBarSubSec3.setForeground(new java.awt.Color(255, 255, 255));
        sideBarSubSec3.setText("Configuration");
        mainBasePanel.add(sideBarSubSec3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        authorName.setFont(new java.awt.Font("Steradian Regular", 0, 14)); // NOI18N
        authorName.setForeground(new java.awt.Color(255, 255, 255));
        authorName.setText("epicX");
        mainBasePanel.add(authorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));

        sideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/sidebarBG.png"))); // NOI18N
        mainBasePanel.add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        chPlainColor.setBackground(new java.awt.Color(28, 28, 40));
        chPlainColor.setForeground(new java.awt.Color(51, 51, 51));
        chPlainColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(28, 28, 40));
        jLabel4.setFont(new java.awt.Font("Steradian Regular", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Choose color");
        chPlainColor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, 268, 54));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Background color");
        chPlainColor.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 76, -1, -1));

        bColor.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        bColor.setForeground(new java.awt.Color(255, 255, 255));
        bColor.setText("#FFFFFF");
        bColor.setBorder(null);
        bColor.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        bColor.setOpaque(false);
        chPlainColor.add(bColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 100, 196, 23));
        bColor.setBackground(null);

        jSeparator1.setBackground(new java.awt.Color(28, 28, 40));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        chPlainColor.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 125, 196, 10));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Accent color");
        chPlainColor.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 146, -1, -1));

        aColor.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        aColor.setForeground(new java.awt.Color(255, 255, 255));
        aColor.setText("#FFFFFF");
        aColor.setBorder(null);
        aColor.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        aColor.setOpaque(false);
        chPlainColor.add(aColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 170, 196, 23));
        aColor.setBackground(null);

        jSeparator2.setBackground(new java.awt.Color(28, 28, 40));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        chPlainColor.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 195, 196, 10));

        jSeparator3.setBackground(new java.awt.Color(28, 28, 40));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        chPlainColor.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 265, 196, 10));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Primary text color");
        chPlainColor.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 216, -1, -1));

        pTextColor.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        pTextColor.setForeground(new java.awt.Color(255, 255, 255));
        pTextColor.setText("#FFFFFF");
        pTextColor.setBorder(null);
        pTextColor.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        pTextColor.setOpaque(false);
        chPlainColor.add(pTextColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 240, 196, 23));
        pTextColor.setBackground(null);

        sTextColor.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        sTextColor.setForeground(new java.awt.Color(255, 255, 255));
        sTextColor.setText("#FFFFFF");
        sTextColor.setBorder(null);
        sTextColor.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        sTextColor.setOpaque(false);
        chPlainColor.add(sTextColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 310, 196, 23));
        sTextColor.setBackground(null);

        jSeparator4.setBackground(new java.awt.Color(28, 28, 40));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        chPlainColor.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 335, 196, 10));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Secondary text color");
        chPlainColor.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 286, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dashboard icon color");
        chPlainColor.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 351, -1, -1));

        dColor1.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        dColor1.setForeground(new java.awt.Color(255, 255, 255));
        dColor1.setText("#FFFFFF");
        dColor1.setBorder(null);
        dColor1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        dColor1.setOpaque(false);
        chPlainColor.add(dColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 380, 196, 23));
        dColor1.setBackground(null);

        dColor1S.setBackground(new java.awt.Color(28, 28, 40));
        dColor1S.setForeground(new java.awt.Color(51, 51, 51));
        chPlainColor.add(dColor1S, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 405, 196, 10));

        dColorLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        dColorLabel.setForeground(new java.awt.Color(255, 255, 255));
        dColorLabel.setText("Simple");
        chPlainColor.add(dColorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 351, 69, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/toggleOff.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        chPlainColor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 351, -1, -1));

        dColor2.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        dColor2.setForeground(new java.awt.Color(255, 255, 255));
        dColor2.setText("#FFFFFF");
        dColor2.setBorder(null);
        dColor2.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        dColor2.setOpaque(false);
        chPlainColor.add(dColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 380, 196, 23));
        dColor2.setVisible(false);
        dColor2.setBackground(null);

        dColor2S.setBackground(new java.awt.Color(28, 28, 40));
        dColor2S.setForeground(new java.awt.Color(51, 51, 51));
        chPlainColor.add(dColor2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 405, 196, 10));
        dColor2S.setVisible(false);

        dColor3.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        dColor3.setForeground(new java.awt.Color(255, 255, 255));
        dColor3.setText("#FFFFFF");
        dColor3.setBorder(null);
        dColor3.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        dColor3.setOpaque(false);
        chPlainColor.add(dColor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 426, 196, 23));
        dColor3.setVisible(false);
        dColor3.setBackground(null);

        dColor3S.setBackground(new java.awt.Color(28, 28, 40));
        dColor3S.setForeground(new java.awt.Color(51, 51, 51));
        chPlainColor.add(dColor3S, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 451, 196, 10));
        dColor3S.setVisible(false);

        dColor4S.setBackground(new java.awt.Color(28, 28, 40));
        dColor4S.setForeground(new java.awt.Color(51, 51, 51));
        chPlainColor.add(dColor4S, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 451, 196, 10));
        dColor4S.setVisible(false);

        dColor4.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        dColor4.setForeground(new java.awt.Color(255, 255, 255));
        dColor4.setText("#FFFFFF");
        dColor4.setBorder(null);
        dColor4.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        dColor4.setOpaque(false);
        chPlainColor.add(dColor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 426, 196, 23));
        dColor4.setVisible(false);
        dColor4.setBackground(null);

        dColor5S.setBackground(new java.awt.Color(28, 28, 40));
        dColor5S.setForeground(new java.awt.Color(51, 51, 51));
        chPlainColor.add(dColor5S, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 497, 196, 10));
        dColor5S.setVisible(false);

        dColor5.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        dColor5.setForeground(new java.awt.Color(255, 255, 255));
        dColor5.setText("#FFFFFF");
        dColor5.setBorder(null);
        dColor5.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        dColor5.setOpaque(false);
        chPlainColor.add(dColor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 472, 196, 23));
        dColor5.setVisible(false);
        dColor5.setBackground(null);

        dColor6S.setBackground(new java.awt.Color(28, 28, 40));
        dColor6S.setForeground(new java.awt.Color(51, 51, 51));
        chPlainColor.add(dColor6S, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 497, 196, 10));
        dColor6S.setVisible(false);

        dColor6.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        dColor6.setForeground(new java.awt.Color(255, 255, 255));
        dColor6.setText("#FFFFFF");
        dColor6.setBorder(null);
        dColor6.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        dColor6.setOpaque(false);
        chPlainColor.add(dColor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 472, 196, 23));
        dColor6.setVisible(false);
        dColor6.setBackground(null);

        plainNextBtn.setForeground(new java.awt.Color(255, 255, 255));
        plainNextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/btn.png"))); // NOI18N
        plainNextBtn.setBorder(null);
        plainNextBtn.setBorderPainted(false);
        plainNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plainNextBtnActionPerformed(evt);
            }
        });
        chPlainColor.add(plainNextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, 24));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        chPlainColor.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 508, 401, 35));

        mainBasePanel.add(chPlainColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 540, 570));

        chGradientColor.setBackground(new java.awt.Color(28, 28, 40));
        chGradientColor.setForeground(new java.awt.Color(255, 255, 255));
        chGradientColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(28, 28, 40));
        jLabel11.setFont(new java.awt.Font("Steradian Regular", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Choose color");
        chGradientColor.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, 268, 54));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Background color");
        chGradientColor.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 76, -1, -1));

        gbColor.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        gbColor.setForeground(new java.awt.Color(255, 255, 255));
        gbColor.setText("#FFFFFF");
        gbColor.setBorder(null);
        gbColor.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        gbColor.setOpaque(false);
        chGradientColor.add(gbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 100, 196, 23));
        gbColor.setBackground(null);

        jSeparator5.setBackground(new java.awt.Color(28, 28, 40));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        chGradientColor.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 125, 196, 10));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Second accent color");
        chGradientColor.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 146, -1, -1));

        gaColor.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        gaColor.setForeground(new java.awt.Color(255, 255, 255));
        gaColor.setText("#FFFFFF");
        gaColor.setBorder(null);
        gaColor.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        gaColor.setOpaque(false);
        chGradientColor.add(gaColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 170, 196, 23));
        gaColor.setBackground(null);

        gaColor1S.setBackground(new java.awt.Color(28, 28, 40));
        gaColor1S.setForeground(new java.awt.Color(51, 51, 51));
        chGradientColor.add(gaColor1S, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 195, 196, 10));

        jSeparator7.setBackground(new java.awt.Color(28, 28, 40));
        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        chGradientColor.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 265, 196, 10));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Primary text color");
        chGradientColor.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 216, -1, -1));

        gpTextColor.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        gpTextColor.setForeground(new java.awt.Color(255, 255, 255));
        gpTextColor.setText("#FFFFFF");
        gpTextColor.setBorder(null);
        gpTextColor.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        gpTextColor.setOpaque(false);
        chGradientColor.add(gpTextColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 240, 196, 23));
        gpTextColor.setBackground(null);

        gsTextColor.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        gsTextColor.setForeground(new java.awt.Color(255, 255, 255));
        gsTextColor.setText("#FFFFFF");
        gsTextColor.setBorder(null);
        gsTextColor.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        gsTextColor.setOpaque(false);
        chGradientColor.add(gsTextColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 310, 196, 23));
        gsTextColor.setBackground(null);

        jSeparator8.setBackground(new java.awt.Color(28, 28, 40));
        jSeparator8.setForeground(new java.awt.Color(51, 51, 51));
        chGradientColor.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 335, 196, 10));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Secondary text color");
        chGradientColor.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 286, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Dashboard icon color");
        chGradientColor.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 351, -1, -1));

        gdColor1.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        gdColor1.setForeground(new java.awt.Color(255, 255, 255));
        gdColor1.setText("#FFFFFF");
        gdColor1.setBorder(null);
        gdColor1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        gdColor1.setOpaque(false);
        chGradientColor.add(gdColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 380, 196, 23));
        gdColor1.setBackground(null);

        gdColor1S.setBackground(new java.awt.Color(28, 28, 40));
        gdColor1S.setForeground(new java.awt.Color(51, 51, 51));
        chGradientColor.add(gdColor1S, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 405, 196, 10));

        gdColorLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        gdColorLabel.setForeground(new java.awt.Color(255, 255, 255));
        gdColorLabel.setText("Simple");
        chGradientColor.add(gdColorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 351, 77, -1));

        gcolorSwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/toggleOff.png"))); // NOI18N
        gcolorSwitch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gcolorSwitchMouseClicked(evt);
            }
        });
        chGradientColor.add(gcolorSwitch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 351, -1, -1));

        gdColor2.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        gdColor2.setForeground(new java.awt.Color(255, 255, 255));
        gdColor2.setText("#FFFFFF");
        gdColor2.setBorder(null);
        gdColor2.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        gdColor2.setOpaque(false);
        chGradientColor.add(gdColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 380, 196, 23));
        gdColor2.setBackground(null);

        gdColor2S.setBackground(new java.awt.Color(28, 28, 40));
        gdColor2S.setForeground(new java.awt.Color(51, 51, 51));
        chGradientColor.add(gdColor2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 405, 196, 10));

        gdColor3.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        gdColor3.setForeground(new java.awt.Color(255, 255, 255));
        gdColor3.setText("#FFFFFF");
        gdColor3.setBorder(null);
        gdColor3.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        gdColor3.setOpaque(false);
        chGradientColor.add(gdColor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 426, 196, 23));
        gdColor3.setVisible(false);
        gdColor3.setBackground(null);

        gdColor3S.setBackground(new java.awt.Color(28, 28, 40));
        gdColor3S.setForeground(new java.awt.Color(51, 51, 51));
        chGradientColor.add(gdColor3S, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 451, 196, 10));
        gdColor3S.setVisible(false);

        gdColor4S.setBackground(new java.awt.Color(28, 28, 40));
        gdColor4S.setForeground(new java.awt.Color(51, 51, 51));
        chGradientColor.add(gdColor4S, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 451, 196, 10));
        gdColor4S.setVisible(false);

        gdColor4.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        gdColor4.setForeground(new java.awt.Color(255, 255, 255));
        gdColor4.setText("#FFFFFF");
        gdColor4.setBorder(null);
        gdColor4.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        gdColor4.setOpaque(false);
        chGradientColor.add(gdColor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 426, 196, 23));
        gdColor4.setVisible(false);
        gdColor4.setBackground(null);

        gdColor5S.setBackground(new java.awt.Color(28, 28, 40));
        gdColor5S.setForeground(new java.awt.Color(51, 51, 51));
        chGradientColor.add(gdColor5S, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 497, 196, 10));
        gdColor5S.setVisible(false);

        gdColor5.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        gdColor5.setForeground(new java.awt.Color(255, 255, 255));
        gdColor5.setText("#FFFFFF");
        gdColor5.setBorder(null);
        gdColor5.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        gdColor5.setOpaque(false);
        chGradientColor.add(gdColor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 472, 196, 23));
        gdColor5.setVisible(false);
        gdColor5.setBackground(null);

        gdColor6S.setBackground(new java.awt.Color(28, 28, 40));
        gdColor6S.setForeground(new java.awt.Color(51, 51, 51));
        chGradientColor.add(gdColor6S, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 497, 196, 10));
        gdColor6S.setVisible(false);

        gdColor6.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        gdColor6.setForeground(new java.awt.Color(255, 255, 255));
        gdColor6.setText("#FFFFFF");
        gdColor6.setBorder(null);
        gdColor6.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        gdColor6.setOpaque(false);
        chGradientColor.add(gdColor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 472, 196, 23));
        gdColor6.setVisible(false);
        gdColor6.setBackground(null);

        gbColorType.add(lrBtn);
        lrBtn.setForeground(new java.awt.Color(255, 255, 255));
        lrBtn.setText("LR");
        lrBtn.setToolTipText("");
        lrBtn.setBorder(null);
        lrBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chGradientColor.add(lrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 525, 53, -1));
        lrBtn.setBackground(null);

        gbColorType.add(tbBtn);
        tbBtn.setForeground(new java.awt.Color(255, 255, 255));
        tbBtn.setText("TB");
        tbBtn.setToolTipText("");
        tbBtn.setBorder(null);
        tbBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chGradientColor.add(tbBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 525, 53, -1));
        tbBtn.setBackground(null);

        gbColorType.add(tlbrBtn);
        tlbrBtn.setForeground(new java.awt.Color(255, 255, 255));
        tlbrBtn.setText("TLBR");
        tlbrBtn.setToolTipText("");
        tlbrBtn.setBorder(null);
        tlbrBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chGradientColor.add(tlbrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 525, 63, -1));
        tlbrBtn.setBackground(null);

        gbColorType.add(trblBtn);
        trblBtn.setForeground(new java.awt.Color(255, 255, 255));
        trblBtn.setText("TRBL");
        trblBtn.setToolTipText("");
        trblBtn.setBorder(null);
        trblBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chGradientColor.add(trblBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 525, 53, -1));
        trblBtn.setBackground(null);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gradient Type");
        chGradientColor.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 523, -1, -1));

        gaColor2.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        gaColor2.setForeground(new java.awt.Color(255, 255, 255));
        gaColor2.setText("#FFFFFF");
        gaColor2.setBorder(null);
        gaColor2.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        gaColor2.setOpaque(false);
        chGradientColor.add(gaColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 170, 196, 23));
        gaColor2.setBackground(null);

        gaColor2S.setBackground(new java.awt.Color(28, 28, 40));
        gaColor2S.setForeground(new java.awt.Color(51, 51, 51));
        chGradientColor.add(gaColor2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 195, 196, 10));

        gradientButton.setForeground(new java.awt.Color(255, 255, 255));
        gradientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/btn.png"))); // NOI18N
        gradientButton.setBorder(null);
        gradientButton.setBorderPainted(false);
        gradientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradientButtonActionPerformed(evt);
            }
        });
        chGradientColor.add(gradientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, 24));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Accent color");
        chGradientColor.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 146, -1, -1));

        mainBasePanel.add(chGradientColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 540, 570));
        chGradientColor.setVisible(false);

        configurationPanel.setBackground(new java.awt.Color(28, 28, 40));
        configurationPanel.setForeground(new java.awt.Color(255, 255, 255));
        configurationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(28, 28, 40));
        jLabel18.setFont(new java.awt.Font("Steradian Regular", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Configuration");
        configurationPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, 268, 54));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Dashboard icon style");
        configurationPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 146, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nav-Bar Icon style");
        configurationPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 211, -1, -1));

        executeBtn.setForeground(new java.awt.Color(255, 255, 255));
        executeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/executeBtn.png"))); // NOI18N
        executeBtn.setBorder(null);
        executeBtn.setBorderPainted(false);
        executeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeBtnActionPerformed(evt);
            }
        });
        configurationPanel.add(executeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, 24));

        dType.add(dIcoDefault);
        dIcoDefault.setForeground(new java.awt.Color(255, 255, 255));
        dIcoDefault.setText("Default");
        dIcoDefault.setBorder(null);
        configurationPanel.add(dIcoDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 175, -1, -1));
        dIcoDefault.setBackground(null);

        dType.add(dIcoMaterial);
        dIcoMaterial.setForeground(new java.awt.Color(255, 255, 255));
        dIcoMaterial.setText("Material");
        dIcoMaterial.setBorder(null);
        configurationPanel.add(dIcoMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 175, -1, -1));
        dIcoMaterial.setBackground(null);

        dType.add(dIcoPlain);
        dIcoPlain.setForeground(new java.awt.Color(255, 255, 255));
        dIcoPlain.setText("Plain");
        dIcoPlain.setBorder(null);
        configurationPanel.add(dIcoPlain, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 175, -1, -1));
        dIcoPlain.setBackground(null);

        nType.add(nIcoPie);
        nIcoPie.setForeground(new java.awt.Color(255, 255, 255));
        nIcoPie.setText("Pie");
        nIcoPie.setBorder(null);
        configurationPanel.add(nIcoPie, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 240, -1, -1));
        nIcoPie.setBackground(null);

        nType.add(nIcoNxtbit);
        nIcoNxtbit.setForeground(new java.awt.Color(255, 255, 255));
        nIcoNxtbit.setText("Nxt-Bit");
        nIcoNxtbit.setBorder(null);
        configurationPanel.add(nIcoNxtbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 240, -1, -1));
        nIcoNxtbit.setBackground(null);

        nType.add(nIcoSamsung);
        nIcoSamsung.setForeground(new java.awt.Color(255, 255, 255));
        nIcoSamsung.setText("Samsung");
        nIcoSamsung.setBorder(null);
        configurationPanel.add(nIcoSamsung, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 240, -1, -1));
        nIcoSamsung.setBackground(null);

        nType.add(nIcoCustom);
        nIcoCustom.setForeground(new java.awt.Color(255, 255, 255));
        nIcoCustom.setText("Custom");
        nIcoCustom.setBorder(null);
        configurationPanel.add(nIcoCustom, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 240, -1, -1));
        nIcoCustom.setBackground(null);

        prevBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/prevBtn.png"))); // NOI18N
        prevBtn.setBorder(null);
        prevBtn.setBorderPainted(false);
        prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtnActionPerformed(evt);
            }
        });
        configurationPanel.add(prevBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 520, -1, 24));

        mExecuteStatus.setBackground(new java.awt.Color(28, 28, 40));
        mExecuteStatus.setFont(new java.awt.Font("Steradian Regular", 0, 24)); // NOI18N
        mExecuteStatus.setForeground(new java.awt.Color(255, 255, 255));
        mExecuteStatus.setText("Ready");
        configurationPanel.add(mExecuteStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 284, 268, 54));

        sExecuteStatus.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        sExecuteStatus.setForeground(new java.awt.Color(255, 255, 255));
        sExecuteStatus.setText("Click Execute to generate the theme.");
        configurationPanel.add(sExecuteStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 344, -1, -1));

        thNameLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        thNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        thNameLabel.setText("Theme name");
        configurationPanel.add(thNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 76, -1, -1));

        thName.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        thName.setForeground(new java.awt.Color(255, 255, 255));
        thName.setText("Goon Theme");
        thName.setBorder(null);
        thName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        thName.setOpaque(false);
        configurationPanel.add(thName, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 100, 196, 23));
        thName.setBackground(null);

        thNameS.setBackground(new java.awt.Color(28, 28, 40));
        thNameS.setForeground(new java.awt.Color(51, 51, 51));
        configurationPanel.add(thNameS, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 125, 196, 10));

        cleanupBtn.setForeground(new java.awt.Color(255, 255, 255));
        cleanupBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cleanupBtn.png"))); // NOI18N
        cleanupBtn.setBorder(null);
        cleanupBtn.setBorderPainted(false);
        cleanupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanupBtnActionPerformed(evt);
            }
        });
        configurationPanel.add(cleanupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, -1, 24));

        mainBasePanel.add(configurationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 540, 570));
        configurationPanel.setVisible(false);

        versionLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(255, 255, 255));
        versionLabel.setText("ver 2.3 beta");
        mainBasePanel.add(versionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 70, -1));

        helpHeader.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        helpHeader.setForeground(new java.awt.Color(255, 255, 255));
        helpHeader.setText("Help");

        helpSubTxt1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        helpSubTxt1.setForeground(new java.awt.Color(255, 255, 255));
        helpSubTxt1.setText("LR: Left to Right");

        helpSubTxt2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        helpSubTxt2.setForeground(new java.awt.Color(255, 255, 255));
        helpSubTxt2.setText("TB: Top to Bottom");

        helpSubTxt3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        helpSubTxt3.setForeground(new java.awt.Color(255, 255, 255));
        helpSubTxt3.setText("TRBL: TopLeft to BottomRight");

        helpSubTxt4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        helpSubTxt4.setForeground(new java.awt.Color(255, 255, 255));
        helpSubTxt4.setText("TLBR: TopRight to BottomLeft");

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(helpHeader)
                    .addComponent(helpSubTxt1)
                    .addComponent(helpSubTxt2)
                    .addComponent(helpSubTxt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(helpSubTxt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpHeader)
                .addGap(8, 8, 8)
                .addComponent(helpSubTxt1)
                .addGap(11, 11, 11)
                .addComponent(helpSubTxt2)
                .addGap(11, 11, 11)
                .addComponent(helpSubTxt3)
                .addGap(11, 11, 11)
                .addComponent(helpSubTxt4)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        mainBasePanel.add(helpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 200, 470));
        helpPanel.setVisible(false);
        helpPanel.setBackground(null);

        closeBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/closeBtn.png"))); // NOI18N
        closeBtn1.setBorderPainted(false);
        closeBtn1.setContentAreaFilled(false);
        closeBtn1.setFocusPainted(false);
        closeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtn1ActionPerformed(evt);
            }
        });
        mainBasePanel.add(closeBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 10, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minBtnActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minBtnActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(randomDashBoardColor){
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/toggleOff.png")));
            dColorLabel.setText("Simple");
            dColor2.setVisible(false);
            dColor2S.setVisible(false);
            dColor3.setVisible(false);
            dColor3S.setVisible(false);
            dColor4.setVisible(false);
            dColor4S.setVisible(false);
            dColor5.setVisible(false);
            dColor5S.setVisible(false);
            dColor6.setVisible(false);
            dColor6S.setVisible(false);
            randomDashBoardColor=false;
            
        }else{
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/toggleOn.png")));
            dColorLabel.setText("Random");
            dColor2.setVisible(true);
            dColor2S.setVisible(true);
            dColor3.setVisible(true);
            dColor3S.setVisible(true);
            dColor4.setVisible(true);
            dColor4S.setVisible(true);
            dColor5.setVisible(true);
            dColor5S.setVisible(true);
            dColor6.setVisible(true);
            dColor6S.setVisible(true);
            randomDashBoardColor=true;
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void colorTypeSwitcherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorTypeSwitcherMouseClicked
        if(gradientColor){
            gradientColor=false;
            colorTypeSwitcher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/toggleOff.png")));
            sideBarSubSec1.setText("Plain Color");
            chGradientColor.setVisible(false);
            helpPanel.setVisible(false);
            chPlainColor.setVisible(true);
        }else{
            gradientColor=true;
            colorTypeSwitcher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/toggleOn.png")));
            sideBarSubSec1.setText("Gradient Color");
            chPlainColor.setVisible(false);
            helpPanel.setVisible(true);
            chGradientColor.setVisible(true);
        }
    }//GEN-LAST:event_colorTypeSwitcherMouseClicked

    private void gcolorSwitchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gcolorSwitchMouseClicked
        if(grandomDashBoardColor){
            gcolorSwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/toggleOff.png")));
            gdColorLabel.setText("Simple");
            gdColor3.setVisible(false);
            gdColor3S.setVisible(false);
            gdColor4.setVisible(false);
            gdColor4S.setVisible(false);
            gdColor5.setVisible(false);
            gdColor5S.setVisible(false);
            gdColor6.setVisible(false);
            gdColor6S.setVisible(false);
            grandomDashBoardColor=false;
            
        }else{
            gcolorSwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/toggleOn.png")));
            gdColorLabel.setText("Random");
            gdColor3.setVisible(true);
            gdColor3S.setVisible(true);
            gdColor4.setVisible(true);
            gdColor4S.setVisible(true);
            gdColor5.setVisible(true);
            gdColor5S.setVisible(true);
            gdColor6.setVisible(true);
            gdColor6S.setVisible(true);
            grandomDashBoardColor=true;
        }
    }//GEN-LAST:event_gcolorSwitchMouseClicked

    private void plainNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plainNextBtnActionPerformed
        colorTypeSwitcher.setVisible(false);
        colorSelected.setVisible(false);
        configSelected.setVisible(true);
        chPlainColor.setVisible(false);
        configurationPanel.setVisible(true);
    }//GEN-LAST:event_plainNextBtnActionPerformed

    private void gradientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradientButtonActionPerformed
        colorTypeSwitcher.setVisible(false);
        colorSelected.setVisible(false);
        configSelected.setVisible(true);
        chGradientColor.setVisible(false);
        configurationPanel.setVisible(true);
    }//GEN-LAST:event_gradientButtonActionPerformed

    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
        colorTypeSwitcher.setVisible(true);
        colorSelected.setVisible(true);
        configSelected.setVisible(false);
        if(gradientColor){
            chGradientColor.setVisible(true);
        }else{
            chPlainColor.setVisible(true);
        }
        configurationPanel.setVisible(false);
    }//GEN-LAST:event_prevBtnActionPerformed

    private void executeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeBtnActionPerformed
        mExecuteStatus.setForeground(normalColor);
        mExecuteStatus.setText("Processing");
        if(verifyData()){
            try {
                genarateTheme();
                
            } catch (IOException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                mExecuteStatus.setForeground(successColor);
                sExecuteStatus.setForeground(normalColor);
                mExecuteStatus.setText("Done");
                sExecuteStatus.setText("Theme generated Successfully");
            }
        }else{
            mExecuteStatus.setForeground(failedColor);
            mExecuteStatus.setText("Failed");
        }
    }//GEN-LAST:event_executeBtnActionPerformed

    private void topBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMouseDragged
        setLocation(getLocation().x + evt.getX() - mpX,getLocation().y + evt.getY() - mpY );
    }//GEN-LAST:event_topBarMouseDragged

    private void topBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_topBarMouseClicked

    private void topBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMousePressed
        mpX = evt.getX();
        mpY = evt.getY();
    }//GEN-LAST:event_topBarMousePressed

    private void closeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtn1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeBtn1ActionPerformed

    private void cleanupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanupBtnActionPerformed
        Runtime run=Runtime.getRuntime();
        try {
            run.exec("cleanup.exe");
        } catch (IOException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            mExecuteStatus.setForeground(normalColor);
            sExecuteStatus.setForeground(normalColor);
            mExecuteStatus.setText("Ready");
            sExecuteStatus.setText("Cleanup Completed");
        }
    }//GEN-LAST:event_cleanupBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new main().setVisible(true);
        });
    }
    boolean verifyColor(String color){
        if(color.length()==7||color.length()==9){
            return color.charAt(0)=='#';
        }else{
            return false;
        }
    }
    int getDType(){
        if(dIcoDefault.isSelected()){
            return 1;
        }else if(dIcoMaterial.isSelected()){
            return 2;
        }else if(dIcoPlain.isSelected()){
            return 3;
        }else{
            return 0;
        }
    }
    int getNType(){
        if(nIcoPie.isSelected()){
            return 1;
        }else if(nIcoNxtbit.isSelected()){
            return 2;
        }else if(nIcoSamsung.isSelected()){
            return 3;
        }else if(nIcoCustom.isSelected()){
            return 4;
        }else{
            return 0;
        }
    }
    int getGType(){
        if(lrBtn.isSelected()){
            return 1;
        }else if(tbBtn.isSelected()){
            return 2;
        }else if(tlbrBtn.isSelected()){
            return 3;
        }else if(trblBtn.isSelected()){
            return 4;
        }else{
            return 0;
        }
    }
    boolean verifyData(){
        if(gradientColor){
            if(verifyColor(gbColor.getText())&&verifyColor(gaColor.getText())&&verifyColor(gpTextColor.getText())&&verifyColor(gsTextColor.getText())&&verifyColor(gdColor1.getText())&&verifyColor(gdColor2.getText())){
                if(grandomDashBoardColor){
                    if(verifyColor(dColor3.getText())&&verifyColor(dColor4.getText())&&verifyColor(dColor5.getText())&&verifyColor(dColor6.getText())){
                    }else{
                        sExecuteStatus.setForeground(failedColor);
                        sExecuteStatus.setText("All Random Colors not correct.");
                        return false;
                    }
                }
                if(getDType()==0||getNType()==0){
                    sExecuteStatus.setForeground(failedColor);
                    sExecuteStatus.setText("Necessary Options are not checked....");
                    return false;
                }
                if(getGType()==0){
                    sExecuteStatus.setForeground(failedColor);
                    sExecuteStatus.setText("Gradient type is not configured yet....");
                    return false;
                }
                return true;
            }else{
                sExecuteStatus.setForeground(failedColor);
                sExecuteStatus.setText("Necessary Colors are incorrect....");
                return false;
            }
        }else{
            if(verifyColor(bColor.getText())&&verifyColor(aColor.getText())&&verifyColor(pTextColor.getText())&&verifyColor(sTextColor.getText())&&verifyColor(dColor1.getText())){
                if(randomDashBoardColor){
                    if(verifyColor(dColor2.getText())&&verifyColor(dColor3.getText())&&verifyColor(dColor4.getText())&&verifyColor(dColor5.getText())&&verifyColor(dColor6.getText())){
                    }else{
                        sExecuteStatus.setForeground(failedColor);
                        sExecuteStatus.setText("All Random Colors not correct.");
                        return false;
                    }
                }
                if(getDType()==0||getNType()==0){
                    sExecuteStatus.setForeground(failedColor);
                    sExecuteStatus.setText("Necessary Options are not checked....");
                    return false;
                }
                return true;
            }else{
                sExecuteStatus.setForeground(failedColor);
                sExecuteStatus.setText("Necessary Colors are incorrect....");
                return false;
            }
        }
    }
    boolean genarateTheme()throws IOException{
        if(gradientColor){
            if(grandomDashBoardColor){
                Operation Omega=new Operation(thName.getText(),gbColor.getText(),gaColor.getText(),gaColor2.getText(),gpTextColor.getText(),gsTextColor.getText(),gdColor1.getText(),gdColor2.getText(),gdColor3.getText(),gdColor4.getText(),gdColor5.getText(),gdColor6.getText(),getDType(),getNType(),getGType(),1);
                Omega.genarateResource();
            }else{
                Operation Omega=new Operation(thName.getText(),gbColor.getText(),gaColor.getText(),gaColor2.getText(),gpTextColor.getText(),gsTextColor.getText(),gdColor1.getText(),gdColor2.getText(),gdColor3.getText(),gdColor4.getText(),gdColor5.getText(),gdColor6.getText(),getDType(),getNType(),getGType(),0);
                Omega.genarateResource();
            }
        }else{
            if(randomDashBoardColor){
                Operation Omega=new Operation(thName.getText(),bColor.getText(),aColor.getText(),pTextColor.getText(),sTextColor.getText(),dColor1.getText(),dColor2.getText(),dColor3.getText(),dColor4.getText(),dColor5.getText(),dColor6.getText(),getDType(),getNType(),1);
                Omega.genarateResource();
            }else{
                Operation Omega=new Operation(thName.getText(),bColor.getText(),aColor.getText(),pTextColor.getText(),sTextColor.getText(),dColor1.getText(),getDType(),getNType(),0);
                Omega.genarateResource();
            }
        }
        
        return true;
    }
    void cleanupTask() throws IOException{
      Runtime run = Runtime.getRuntime();
      run.exec("cleanup.exe");
    }
    void colorParse(String color){
        if(color.length()>8){
            alpha=Integer.parseInt(color.substring(1,3),16);
            red=Integer.parseInt(color.substring(3,5),16);
            green=Integer.parseInt(color.substring(5,7),16);
            blue=Integer.parseInt(color.substring(7,9),16);
        }else{
            alpha=255;
            red=Integer.parseInt(color.substring(1,3),16);
            green=Integer.parseInt(color.substring(3,5),16);
            blue=Integer.parseInt(color.substring(5,7),16);
        }
    }
    int alpha,red,green,blue;
    Color primaryBgColor=new Color(28,28,40);
    Color normalColor=new Color(255,255,255);
    Color failedColor=new Color(255,113,144);
    Color successColor=new Color(0,255,169);
    boolean randomDashBoardColor=false;
    boolean grandomDashBoardColor=false;
    boolean gradientColor=false;
    int mpX,mpY;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aColor;
    private javax.swing.JLabel appLogo;
    private javax.swing.JLabel appTitle;
    private javax.swing.JLabel authorName;
    private javax.swing.JTextField bColor;
    private javax.swing.JPanel chGradientColor;
    private javax.swing.JPanel chPlainColor;
    private javax.swing.JButton cleanupBtn;
    private javax.swing.JButton closeBtn1;
    private javax.swing.JSeparator colorSelected;
    private javax.swing.JLabel colorTypeSwitcher;
    private javax.swing.JSeparator configSelected;
    private javax.swing.JPanel configurationPanel;
    private javax.swing.JTextField dColor1;
    private javax.swing.JSeparator dColor1S;
    private javax.swing.JTextField dColor2;
    private javax.swing.JSeparator dColor2S;
    private javax.swing.JTextField dColor3;
    private javax.swing.JSeparator dColor3S;
    private javax.swing.JTextField dColor4;
    private javax.swing.JSeparator dColor4S;
    private javax.swing.JTextField dColor5;
    private javax.swing.JSeparator dColor5S;
    private javax.swing.JTextField dColor6;
    private javax.swing.JSeparator dColor6S;
    private javax.swing.JLabel dColorLabel;
    private javax.swing.JRadioButton dIcoDefault;
    private javax.swing.JRadioButton dIcoMaterial;
    private javax.swing.JRadioButton dIcoPlain;
    private javax.swing.ButtonGroup dType;
    private javax.swing.JButton executeBtn;
    private javax.swing.JTextField gaColor;
    private javax.swing.JSeparator gaColor1S;
    private javax.swing.JTextField gaColor2;
    private javax.swing.JSeparator gaColor2S;
    private javax.swing.JTextField gbColor;
    private javax.swing.ButtonGroup gbColorType;
    private javax.swing.JLabel gcolorSwitch;
    private javax.swing.JTextField gdColor1;
    private javax.swing.JSeparator gdColor1S;
    private javax.swing.JTextField gdColor2;
    private javax.swing.JSeparator gdColor2S;
    private javax.swing.JTextField gdColor3;
    private javax.swing.JSeparator gdColor3S;
    private javax.swing.JTextField gdColor4;
    private javax.swing.JSeparator gdColor4S;
    private javax.swing.JTextField gdColor5;
    private javax.swing.JSeparator gdColor5S;
    private javax.swing.JTextField gdColor6;
    private javax.swing.JSeparator gdColor6S;
    private javax.swing.JLabel gdColorLabel;
    private javax.swing.JTextField gpTextColor;
    private javax.swing.JButton gradientButton;
    private javax.swing.JTextField gsTextColor;
    private javax.swing.JLabel helpHeader;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JLabel helpSubTxt1;
    private javax.swing.JLabel helpSubTxt2;
    private javax.swing.JLabel helpSubTxt3;
    private javax.swing.JLabel helpSubTxt4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JRadioButton lrBtn;
    private javax.swing.JLabel mExecuteStatus;
    private javax.swing.JPanel mainBasePanel;
    private javax.swing.JButton minBtn;
    private javax.swing.JRadioButton nIcoCustom;
    private javax.swing.JRadioButton nIcoNxtbit;
    private javax.swing.JRadioButton nIcoPie;
    private javax.swing.JRadioButton nIcoSamsung;
    private javax.swing.ButtonGroup nType;
    private javax.swing.JTextField pTextColor;
    private javax.swing.JButton plainNextBtn;
    private javax.swing.JButton prevBtn;
    private javax.swing.JLabel sExecuteStatus;
    private javax.swing.JTextField sTextColor;
    private javax.swing.JLabel sideBar;
    private javax.swing.JLabel sideBarMainSec;
    private javax.swing.JLabel sideBarMainSec2;
    private javax.swing.JLabel sideBarSubSec1;
    private javax.swing.JLabel sideBarSubSec3;
    private javax.swing.JRadioButton tbBtn;
    private javax.swing.JTextField thName;
    private javax.swing.JLabel thNameLabel;
    private javax.swing.JSeparator thNameS;
    private javax.swing.JRadioButton tlbrBtn;
    private javax.swing.JPanel topBar;
    private javax.swing.JRadioButton trblBtn;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
